languageCode = "en-us"
disqusShortname = ""
theme = "idm"
pluralizelisttitles = false
summaryLength = 70
googleAnalytics = ""
defaultContentLanguage = "en"
paginate = 10
title = "Identity Managed"
baseurl = "https://identitymanaged.netlify.app/"

[params]
logo_text = "Identity Managed"
mainSections = ["blog"]
copyright = "Copyright (c) 2023 Identity Managed; all rights reserved."
date_format = "January 2, 2006"
defaultKeywords = ["identity", "hugo", "go"]
author = "David"
logo = "img/logo.webp"
disabled_logo = false
about_us = "<p>We are a US based Identity Management consulting firm focusing on automating provisioning, deprovisioning, synchronization, GRC, SSO, and MFA to large enterprises.</p>"
contact_url = "/contact"
googleRecaptchaKey = "site_key_for_google_recaptcha"
style = "idm"
logo_small = "img/logo-small.webp"
viewMorePostLink = "/blog/"
address = "<p class=\"text-uppercase\"><strong>Identity Managed LLC</strong>\n        \n        <br>\n        <strong>Chandler, AZ</strong>\n      </p>\n      "
enableRecaptchaInContactForm = false
defaultDescription = "Identity Managed"
dropdown_mouse_over = false

[params.see_more]
enable = true
icon = "far fa-file-alt"
title = "Let us lock down your digital fortress"
subtitle = "We have secured over 2.7 million identities. We can do it for you. Book a free 20 min consultation."
link_url = "https://outlook.office365.com/book/IdentityManagedLLC@identitymanaged.com/"
link_text = "Book Time with an Expert"

[params.clients]
enable = true
title = "Our Clients"
subtitle = ""

[params.carouselHomepage]
enable = true
auto_play = true
slide_speed = 2000
pagination_speed = 1000

[params.recent_posts]
enable = true
title = "From our blog"
subtitle = ""
hide_summary = false

[params.widgets]
categories = true
tags = true
search = true

[params.carouselTestimonials]
items = 3
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.testimonials]
enable = true
title = "Testimonials"
subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.carouselCustomers]
items = 6
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.footer]

[params.footer.recent_posts]
enable = true

[params.features]
enable = true
cols = 3

[params.services]
enable = true
cols = 3

[params.topbar]
enable = true
text = "              <button class=\"btn-primary\">\n                <a\n                  href=\"https://outlook.office365.com/book/IdentityManagedLLC@identitymanaged.com/\"\n                  class=\"btn\" style=\"color: white;\"\n                  target=\"_blank\"\n                >\n                  Free Consultation </a></button>\n            "

[permalinks]
blog = "/blog/:year/:month/:filename/"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[menu]

[[menu.main]]
name = "Home"
identifier = "menu.home"
url = "/"
weight = 10

[[menu.main]]
name = "Blog"
identifier = "menu.blog"
url = "/blog/"
weight = 20

[[menu.main]]
name = "FAQ"
identifier = "menu.faq"
url = "/faq/"
weight = 30

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 40

[[menu.topbar]]
weight = 10
name = "LinkedIn"
url = "https://www.linkedin.com/company/identity-managed/"
pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[menu.topbar]]
weight = 20
name = "Twitter"
url = "https://twitter.com/DavidLundell"
pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
weight = 30
name = "YouTube"
url = "https://www.youtube.com/@identitymanaged6788"
pre = "<i class='fab fa-2x fa-brands fa-youtube'></i>"