backend:
  name: git-gateway
  branch: main
# publish_mode: editorial_workflow # optional to review post before publishing
media_folder: "static/img"
public_folder: "/img/"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SEO Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "banner",
          widget: "image",
          required: false,
        }
      - { label: "Authors", name: "authors", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/privacy-policy.md"
        label: "Privacy Policy"
        name: "privacy policy"
        fields:
          - {
              label: Title (Name of Home page tab),
              name: title,
              widget: string,
            }
          - { label: SEO Description, name: description, widget: text }
          - { label: "Body", name: body, widget: markdown }
        #end of privacy policy

      - file: "content/faq.md"
        label: "FAQ"
        name: "faq"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: SEO Description, name: description, widget: text }
          - { label: "Body", name: body, widget: markdown }
        #end of faq

      - file: "content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: SEO Description, name: description, widget: text }
          - { label: "Body", name: body, widget: markdown }
        #end of contact

  - name: "carousel"
    label: "Home Page Carousel"
    description: "The blurb on the items is using HTML tags for effects."
    folder: "data/carousel"
    create: true
    extension: yaml
    slug: "{{title}}"
    fields:
      - {
          label: Order,
          name: weight,
          widget: number,
          value_type: "int",
          min: 1,
          max: 101,
          step: 1,
        }
      - { label: Title, name: title, widget: string }
      - { label: Blurb, name: description, widget: text }
      - { label: Photo, name: image, widget: image, required: false }
      - { label: Link, name: href, widget: string, required: false }

  - name: "testimonials"
    label: "Testimonials"
    folder: "data/testimonials"
    create: true
    extension: yaml
    slug: "{{title}}"
    fields:
      - {
          label: Position,
          name: title,
          widget: number,
          value_type: "int",
          min: 1,
          max: 101,
          step: 1,
        }
      - { label: Name, name: name, widget: string }
      - { label: Testimonial, name: text, widget: text }
      - { label: Photo, name: avatar, widget: image, required: false }

  - name: "clients"
    label: "Clients"
    folder: "data/clients"
    description: "This section resides on the bottom of the home page just above the footer. If blank, this section will not be visible. Recommend adding five clients at once from spacing purposes."
    create: true
    extension: yaml
    slug: "{{title}}"
    fields:
      - {
          label: Position,
          name: title,
          widget: number,
          value_type: "int",
          min: 1,
          max: 101,
          step: 1,
        }
      - { label: Client Name, name: name, widget: string }
      - { label: Website, name: url, widget: string }
      - { label: Logo, name: image, widget: image }
  
  - name: "services"
    label: "Services"
    folder: "data/services"
    description: ""
    create: true
    extension: yaml
    slug: "{{title}}"
    fields:
      - {
          label: Position,
          name: weight,
          widget: number,
          value_type: "int",
          min: 1,
          max: 6,
          step: 1,
        }
      - { label: Headline, name: name, widget: string }
      - { label: Website, name: url, widget: string, required: false }
      - { label: Image, name: image, widget: image }
      - { label: Description, name: description, widget: text }



  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "config.toml"
        label: Site Config
        name: config
        fields:
          - { label: Site URL, name: baseurl, widget: string, required: true }
          - { label: Theme, name: theme, widget: string, required: true }
          - {
              label: Google Analytics tracking code,
              name: googleAnalytics,
              widget: string,
              required: false,
            }
          - {
              label: Disqus Comments,
              name: disqusShortname,
              description: Enable comments by entering your Disqus shortname,
              widget: string,
              required: false,
            }
          - label: Parameters
            name: params
            summary: "Style options: default (light-blue), idm, blue, green, marsala, pink, red, turquoise, violet"
            collapsed: true
            widget: object
            fields:
              - { label: Style Sheet, name: style, widget: string }
              - {
                  label: Address,
                  name: address,
                  widget: string,
                  required: false,
                }
              - { label: About Us, name: about_us, widget: string }
              - { label: Copyright, name: copyright, widget: string }
              - {
                  label: Disable Logo,
                  name: disabled_logo,
                  widget: boolean,
                  default: false,
                }
              - { label: Logo Text, name: logo_text, widget: string }
              - {
                  label: Top Logo (Large Screen),
                  name: logo,
                  widget: image,
                  required: false,
                }
              - {
                  label: Top Logo (Small Screen),
                  name: logo_small,
                  widget: image,
                  required: false,
                }
              - label: Large Call to Action
                name: see_more
                summary: "This is the transparent background, call to action section"
                collapsed: true
                widget: object
                fields:
                  - {
                      label: Enable,
                      name: enable,
                      widget: boolean,
                      default: true,
                    }
                  - { label: Awesome Fonts Icon, name: icon, widget: string }
                  - { label: Headline, name: title, widget: string }
                  - { label: Short Body, name: subtitle, widget: text }
                  - {
                      label: Call to Action URL,
                      name: link_url,
                      widget: string,
                    }
                  - {
                      label: Call to Action Text,
                      name: link_text,
                      widget: string,
                    }

              - label: Services
                name: service
                summary: "This is the transparent background, services section"
                collapsed: true
                widget: object
                fields:
                  - {
                      label: Enable,
                      name: enable,
                      widget: boolean,
                      default: true,
                    }
                    - {
                      label: Columns,
                      name: cols,
                      widget: number,
                      default: 3,
                      value_type: "int",
                      min: 1,
                      max: 6,
                      step: 1,
                    }
                #end of services
                
              - label: Testimonials options
                name: testimonials
                collapsed: true
                widget: object
                fields:
                  - {
                      label: Enable,
                      name: enable,
                      widget: boolean,
                      default: true,
                    }
                  - { label: Headline, name: title, widget: string }
                  - { label: Short Body, name: subtitle, widget: text }
              - label: Testimonials Carousel options
                name: carouselTestimonials
                collapsed: true
                widget: object
                fields:
                  - {
                      label: Show how many at a time,
                      name: items,
                      widget: number,
                      default: 4,
                      value_type: "int",
                      min: 1,
                      max: 6,
                      step: 1,
                    }
                  - {
                      label: Auto Play,
                      name: auto_play,
                      widget: boolean,
                      default: false,
                    }
                  - {
                      label: Slide Speed,
                      name: slide_speed,
                      widget: number,
                      default: 2000,
                      value_type: "int",
                      min: 1000,
                      max: 6000,
                      step: 1000,
                    }
                  - {
                      label: Pagination Speed,
                      name: pagination_speed,
                      widget: number,
                      default: 1000,
                      value_type: "int",
                      min: 1000,
                      max: 6000,
                      step: 1000,
                    }
