backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img/"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SEO Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Featured Image",
          name: "banner",
          widget: "image",
          required: false,
        }
      - { label: "Authors", name: "authors", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "carousel"
    label: "Home Page Carousel"
    description: "The blurb on the items is using HTML tags for effects."
    folder: "data/carousel"
    create: true
    extension: yaml
    slug: "{{title}}"
    fields:
      - {
          label: Order,
          name: weight,
          widget: number,
          value_type: "int",
          min: 1,
          max: 101,
          step: 1,
        }
      - { label: Title, name: title, widget: string }
      - { label: Blurb, name: description, widget: text }
      - { label: Photo, name: image, widget: image, required: false }

  - name: "testimonials"
    label: "Testimonials"
    folder: "data/testimonials"
    create: true
    extension: yaml
    slug: "{{title}}"
    fields:
      - {
          label: Position,
          name: title,
          widget: number,
          value_type: "int",
          min: 1,
          max: 101,
          step: 1,
        }
      - { label: Name, name: name, widget: string }
      - { label: Testimonial, name: text, widget: text }
      - { label: Photo, name: avatar, widget: image, required: false }

  - name: "clients"
    label: "Clients"
    folder: "data/clients"
    description: "This section resides on the bottom of the home page just about the footer. If blank, this section will not be visible. Recommend adding five clients at once from spacing purposes."
    create: true
    extension: yaml
    slug: "{{title}}"
    fields:
      - {
          label: Position,
          name: title,
          widget: number,
          value_type: "int",
          min: 1,
          max: 101,
          step: 1,
        }
      - { label: Client Name, name: name, widget: string }
      - { label: Website, name: url, widget: string }
      - { label: Logo, name: image, widget: image }

  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "config.toml"
        label: Site Config
        name: config
        fields:
          - {
              label: Google Analytics tracking code,
              name: googleAnalytics,
              widget: string,
              required: false,
            }
